name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
    branches: [ $default-branch ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    # TODO consider iterating over apps using matrx
    - name: Core - Install dependencies
      run: go get .
      working-directory: ./core

    - name: Core - Build
      run: go build -v ./...
      working-directory: ./core

    - name: Core - Test
      run: go test -v ./...
      working-directory: ./core

    - name: Fake body - Install dependencies
      run: go get .
      working-directory: ./fake-body

    - name: Fake body - Build
      run: go build -v ./...
      working-directory: ./fake-body

    - name: Fake body - Test
      run: go test -v ./...
      working-directory: ./fake-body